name: Food Receipt Streamlit CI/CD

on:
  push:
    branches: [main, dev]          
    paths:
      - 'src/5_website/backend/**'
      - '.github/workflows/streamlit-cicd.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}/streamlit-app    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push image
      uses: docker/build-push-action@v5
      with:
        context: src/5_website/backend
        file: src/5_website/backend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Deploy via SSH & docker-compose
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      env:
        HOST: ${{ secrets.SSH_HOST }}       
        USER: ${{ secrets.SSH_USER }}       
        KEY:  ${{ secrets.SSH_KEY }}        
        IMAGE_TAG: ${{ github.sha }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "$KEY" > key.pem && chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ${USER}@${HOST} "
          cd /opt/streamlit-app &&
          echo 'IMAGE_TAG=${IMAGE_TAG}' > .env &&
          echo 'OPENAI_API_KEY=${OPENAI_API_KEY}' >> .env &&
          docker compose pull &&
          docker compose up -d
        "
